// HumanMark - Verify human-created content
//
// This module provides a simple API to detect whether content (text, image, audio, video)
// was created by a human or generated by AI.

module github.com/humanmark/humanmark

go 1.22

// No external dependencies for core functionality.
// This keeps the project simple and reduces supply chain risk.
//
// The standard library provides everything we need:
// - net/http for the web server
// - encoding/json for JSON handling
// - crypto/sha256 for content hashing
// - log/slog for structured logging
// - context for request handling
// - sync for thread-safe in-memory storage
//
// Optional dependencies (add when needed):
// - github.com/jackc/pgx/v5 for PostgreSQL
// - github.com/redis/go-redis/v9 for Redis caching
